### ISSUE TITLE
Wraparound Text for Spending

### ISSUE THREAD

**Issue by choongyx** [AY1920S1-CS2103T-F13-3/main#114]
![image](https://user-images.githubusercontent.com/39525563/67624011-5e0c7600-f85e-11e9-9ca9-25c7372500c0.png)

Cost could wrap around if it gets too long or else the cost of other spending cannot be seen (can only be seen once this spending is no longer in view). The same applies for names and remarks.

**Comment by minpyaemoe** [comment]
How about we just increase the size of the card and limit to 2 lines for remark?
