### ISSUE TITLE
UI Bug, very long name overrun the cost label

### ISSUE THREAD

**Issue by minpyaemoe** [AY1920S1-CS2103T-F13-3/main#238]
![image](https://user-images.githubusercontent.com/13093826/68527093-230a4800-031e-11ea-9dbe-503987e11a55.png)

As it can be seen above, a very long name sometimes over run the cost label instead of wrapping.

**Comment by jonathantjendana** [comment]
Fixed, as tag is now limited to not more than 15 characters. #241
