### ISSUE TITLE
UI bug, Pie chart does not show long labels

### ISSUE THREAD

**Issue by minpyaemoe** [AY1920S1-CS2103T-F13-3/main#240]
![image](https://user-images.githubusercontent.com/13093826/68527325-9319cd80-0320-11ea-9fc8-1c0a16348123.png)

As it can be seen in the above picture, if a spending has a very long label, it does not show all the labels including short labels. But it seems to show the data correctly

**Comment by choongyx** [comment]
Have limited tags to 15 chars in new PR.

Do you mind trying to edit the tag to 15 chars on this set of data (if you still have them) and see whether the tags can be seen? To see if the limit of 15 chars work.

Couldn't run the program using the json file from yesterday.

Thanks!

**Comment by minpyaemoe** [comment]
The Pull request from choongyx, #241 fixed this bug
