### ISSUE TITLE
budget command which set monthly budget accepts value which is less than 0.01 which is not actual currency

### ISSUE THREAD

**Issue by minpyaemoe** [AY1920S1-CS2103T-F13-3/main#243]
Budget commands accept value like 0.0001 which is not a actual currency value and the UI update as 0.00 which truncate the remaining digits

**Comment by minpyaemoe** [comment]
I believe you can implement this invalid input check in the same way you implemented error check for negative value input. So, the only valid inputs are currency above or equal to 0.01. Like you mentioned, the valid inputs also include 0 as it is a budget value.

**Comment by choongyx** [comment]
Limit to 2dp as in Cost
