### ISSUE TITLE
Duplicate legend in PPP

### ISSUE THREAD

**Issue by minpyaemoe** [AY1920S1-CS2103T-F13-3/main#245]
![image](https://user-images.githubusercontent.com/13093826/68531516-e5251800-034d-11ea-90fa-357424655e59.png)

The above legends seems to be be appearing again under section, "How to use this guide" in your PPP. May be remove the one under the section, "My role"? Since those legends are not used until "How to use this guide".

**Comment by choongyx** [comment]
Addressed in PR #244

**Comment by choongyx** [comment]
Which is also ready for review :)
